# Hands-On Data Lab

A practical Data Science lab covering NumPy, Pandas, data cleaning, visualization, and basic data analysis.

## Objective

This lab demonstrates a practical Data Science workflow using Python, covering numerical computing, data manipulation, data cleaning, visualization, and basic statistical analysis.

## Dataset

The Titanic passenger dataset is used for hands-on analysis. It contains passenger information such as survival status, passenger class, age, gender, fare, and embarkation port.

## Libraries and Tools

- Python
- Jupyter Notebook
- NumPy
- Pandas
- Matplotlib
- Seaborn

In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## NumPy

NumPy provides efficient array-based operations for numerical computing in Python.

In [59]:
# Create a 1D NumPy array
array = np.array([1, 2, 3, 4, 5, 6])

array.ndim

1

In [60]:
# Create a 1D NumPy array
array.shape

(6,)

In [61]:
# Get the data type of the array
array.dtype

dtype('int64')

In [62]:
array[0]  # Access the first element of the array

np.int64(1)

In [63]:
# Access the last element of the array
array[-1]

np.int64(6)

In [64]:
# Access elements from index 1 to 3
array[1:4]

array([2, 3, 4])

In [65]:
# Reverse the array
array[::-1]

array([6, 5, 4, 3, 2, 1])

In [66]:
# Create a 2D NumPy array
array2 = np.array([[1, 2, 3], [4, 5, 6]])

array2.shape

(2, 3)

In [67]:
# Reshape the array to the specified number of rows and columns
reshaped_array = array.reshape(2, 3)

reshaped_array.shape

(2, 3)

In [68]:
print("Original array:",array)
print("\nReshaped array:\n",reshaped_array)
print("\nShape of the reshaped array:",reshaped_array.shape)

Original array: [1 2 3 4 5 6]

Reshaped array:
 [[1 2 3]
 [4 5 6]]

Shape of the reshaped array: (2, 3)

In [69]:
# Calculate the sum of all elements in the array
print("Sum of all elements in the array:", np.sum(array))

Sum of all elements in the array: 21

In [70]:
# Calculate the mean of all elements in the array
print("Mean of all elements in the array:", np.mean(array))

Mean of all elements in the array: 3.5

In [71]:
# Calculate the standard deviation of all elements in the array
print("Standard deviation of all elements in the array:", np.std(array))

Standard deviation of all elements in the array: 1.707825127659933

In [72]:
# Calculate the maximum value in the array
print("Maximum value in the array:", np.max(array))

Maximum value in the array: 6

In [73]:
# Calculate the minimum value in the array
print("Minimum value in the array:", np.min(array))

Minimum value in the array: 1

### Practical Numerical Data Operation

NumPy can be used to perform condition-based operations on numerical data. In this exercise, passenger ages are analyzed using Boolean indexing to identify values above the average age.

In [74]:
ages = np.array([12, 18, 25, 31, 42, 55, 67, 8])
avg_age = np.mean(ages)
print("Average age:", avg_age)

max_age = np.max(ages)
print("Maximum age:", max_age)

min_age = np.min(ages)
print("Minimum age:", min_age)

print("\nAges greater than average age:", ages[ages > avg_age])  # Filter ages greater than average age

Average age: 32.25
Maximum age: 67
Minimum age: 8

Ages greater than average age: [42 55 67]

## Pandas

Pandas provides flexible data structures and tools for loading, inspecting, manipulating, and analyzing structured data.

In [75]:
fares = pd.Series([7.25, 13.0, 8.05, 71.28, 7.92])
print("Fare Series:\n", fares)  # Access the entire Series
print("Fare values:", fares.values)  # Access the values of the Series
print("Index of the Series:", fares.index)  # Access the index of the Series
print("Data type of the Series:", fares.dtype)  # Access the data type of the Series

Fare Series:
 0     7.25
1    13.00
2     8.05
3    71.28
4     7.92
dtype: float64
Fare values: [ 7.25 13.    8.05 71.28  7.92]
Index of the Series: RangeIndex(start=0, stop=5, step=1)
Data type of the Series: float64

In [76]:
passenger_data = pd.DataFrame({
    "Name": ["Kartikey", "Shivam", "Ankit", "Gopal"],
    "Age": [25, 30, 35, 40],
    "Fare": [7.25, 13.0, 8.05, 71.28]
})

print("DataFrame:\n", passenger_data)  # Access the entire DataFrame
print("DataFrame shape:\n", passenger_data.shape)  # Access the shape of the DataFrame
print("DataFrame columns:\n", passenger_data.columns)  # Access the columns of the DataFrame
print("DataFrame Data Types:\n", passenger_data.dtypes)  # Access the data types of the DataFrame columns

DataFrame:
        Name  Age   Fare
0  Kartikey   25   7.25
1    Shivam   30  13.00
2     Ankit   35   8.05
3     Gopal   40  71.28
DataFrame shape:
 (4, 3)
DataFrame columns:
 Index(['Name', 'Age', 'Fare'], dtype='str')
DataFrame Data Types:
 Name        str
Age       int64
Fare    float64
dtype: object

### Loading the Dataset

The Titanic dataset is loaded into a Pandas DataFrame for inspection, cleaning, manipulation, and analysis.

In [77]:
# Read the Titanic dataset from a CSV file
df = pd.read_csv('../data/train.csv')
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [78]:
# Display the first 5 rows of the DataFrame
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Dataset Inspection

The dataset structure is examined to understand its dimensions, columns, data types, and overall information before further analysis.

In [79]:
# Display the shape of the DataFrame
print("DataFrame shape:", df.shape)

# Display the columns of the DataFrame
print("DataFrame columns:", df.columns)

# Display the data types of the DataFrame columns
print("DataFrame data types:", df.dtypes)

DataFrame shape: (891, 12)
DataFrame columns: Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')
DataFrame data types: PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [80]:
df.info()  # Display concise summary of the DataFrame, including data types and non-null values

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

### Missing Value Inspection

Missing values are identified and quantified to determine which columns require cleaning before analysis.

In [81]:
df.isnull()  # Check for missing values in the DataFrame

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [82]:
print(df.isnull().sum())  # Display the count of missing values in each column of the DataFrame

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### Duplicate Record Inspection

Duplicate records are checked to determine whether the dataset contains repeated observations that could affect the analysis.

In [83]:
# Check for duplicate rows in the DataFrame
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

### Categorical Value Inspection

Categorical columns are examined for unique values to identify unexpected, inconsistent, or incorrectly formatted entries before preprocessing.

In [84]:
# Display unique values in specific columns
print("Unique values in 'Sex' column:", df["Sex"].unique())
print("Unique values in 'Embarked' column:", df["Embarked"].unique())

Unique values in 'Sex' column: <StringArray>
['male', 'female']
Length: 2, dtype: str
Unique values in 'Embarked' column: <StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [85]:
print("Value counts for 'Sex' column:")
print(df["Sex"].value_counts())

print("\nValue counts for 'Embarked' column:")
print(df["Embarked"].value_counts())

Value counts for 'Sex' column:
Sex
male      577
female    314
Name: count, dtype: int64

Value counts for 'Embarked' column:
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

### Numerical Data Inspection

Numerical columns are examined using descriptive statistics to understand their distributions, ranges, and potential data-quality issues.

In [86]:
# Get a summary of the data
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### Missing Age Analysis

The distribution of age is examined across passenger class and sex to determine an appropriate strategy for handling missing age values.

In [87]:
# Fill missing age values with the median age for each passenger class and sex
df.groupby(["Pclass", "Sex"])["Age"].median()

Pclass  Sex
1       female    35.0
        male      40.0
2       female    28.0
        male      30.0
3       female    21.5
        male      25.0
Name: Age, dtype: float64

In [88]:
# Fill missing age values with the median age for each passenger class and sex
df["Age"] = df.groupby(["Pclass", "Sex"])["Age"].transform(
    lambda x: x.fillna(x.median())
    )

df["Age"].isnull().sum()

np.int64(0)

### Handling Missing Embarkation Values

Missing values in the categorical `Embarked` column are handled using the most frequent category after examining its distribution.

In [89]:
# Fill missing embarked values with the most common value
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [90]:
df["Embarked"].isnull().sum()

np.int64(0)

### Cabin Missingness Analysis

The extent of missing values in the `Cabin` column is examined before deciding whether the column should be retained, transformed, or excluded from the analysis.

In [91]:
# check for missing values in the "Cabin" column
df["Cabin"].isnull().sum()

np.int64(687)

In [92]:
# Calculate the percentage of missing values in the "Cabin" column
missing_cabin_pct = df["Cabin"].isnull().sum() / len(df) * 100
print("Missing Cabin percentage:", missing_cabin_pct)

Missing Cabin percentage: 77.10437710437711

In [93]:
# Remove the "Cabin" column from the dataset
cleaned_df = df.copy()
cleaned_df = cleaned_df.drop(columns=["Cabin"])

print("Original shape:", df.shape)
print("Cleaned shape:", cleaned_df.shape)

Original shape: (891, 12)
Cleaned shape: (891, 11)

In [94]:
# Check for missing values in the cleaned DataFrame
cleaned_df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [95]:
# Compare the shapes of the original and cleaned datasets
print("Original dataset shape:", df.shape)
print("Cleaned dataset shape:", cleaned_df.shape)

print("\nRemoved columns:")
print(set(df.columns) - set(cleaned_df.columns))

Original dataset shape: (891, 12)
Cleaned dataset shape: (891, 11)

Removed columns:
{'Cabin'}

In [96]:
# Create a new column "FamilySize" by adding "SibSp" and "Parch" columns
cleaned_df["FamilySize"] = cleaned_df["SibSp"] + cleaned_df["Parch"] + 1

cleaned_df[["SibSp", "Parch", "FamilySize"]].head()

   SibSp  Parch  FamilySize
0      1      0           2
1      1      0           2
2      0      0           1
3      1      0           2
4      0      0           1

In [97]:
# Display the value counts of the "FamilySize" column in the cleaned DataFrame
cleaned_df["FamilySize"].value_counts().sort_index()

FamilySize
1     537
2     161
3     102
4      29
5      15
6      22
7      12
8       6
11      7
Name: count, dtype: int64

In [102]:
# Create a new column "FamilyType" based on the "FamilySize" column
conditions = [
    cleaned_df["FamilySize"] == 1,
    cleaned_df["FamilySize"].between(2, 4),
    cleaned_df["FamilySize"] >= 5
]

choices = ["Alone", "Small Family", "Large Family"]

cleaned_df["FamilyType"] = np.select(
    conditions,
    choices,
    default="Unknown"
)

In [ ]:
# Display the first 10 rows of the "FamilySize" and "FamilyType" columns
cleaned_df[["FamilySize", "FamilyType"]].head(10)

   FamilySize    FamilyType
0           2  Small Family
1           2  Small Family
2           1         Alone
3           2  Small Family
4           1         Alone
5           1         Alone
6           1         Alone
7           5  Large Family
8           3  Small Family
9           2  Small Family

In [105]:
# Display the value counts of the "FamilyType" column in the cleaned DataFrame
cleaned_df["FamilyType"].value_counts()

FamilyType
Alone           537
Small Family    292
Large Family     62
Name: count, dtype: int64

In [108]:
# Save the cleaned DataFrame to a new CSV file
cleaned_df.to_csv("../data/titanic_cleaned.csv", index=False)